import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  header: {
    padding: 24,
    backgroundColor: '#131016',
    width: '100%',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingBottom: -64,
    marginBottom: 32,
  },
  logo: {
    width: 110.34,
    height: 32,
    marginTop: 48,
  },
  form: {
    width: '100%',
    flexDirection: 'row',
    marginTop: 36,
    marginBottom: -24,
  },
  summary: {
    marginTop: 24,
    paddingHorizontal: 24,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  createdText: {
    color: '#4EA8DE',
    fontSize: 24,
    fontWeight: 'bold',
    marginRight: 8,
  },
  finishedText: {
    color: '#7577DE',
    fontSize: 24,
    fontWeight: 'bold',
    marginRight: 8,
  },
  summaryItem: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  hairlineWidth: {
    width: '90%',
    height: 1,
    backgroundColor: '#333333',
    margin: 16,
  },
  taskCounter: {
    width: 32,
    height: 24,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#333333',
    borderRadius: 16,
  },
  counterText: {
    color: '#fff',
    alignItems: 'center',
    fontSize: 16,
    fontWeight: 'bold',
  },
  title: {
    color: '#FFF',
    fontSize: 32,
    fontWeight: 'bold',
    marginTop: 48,
  },
  progressText: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 48,
  },
  progress: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 8,
  },
  input: {
    flex: 1,
    height: 56,
    backgroundColor: '#1F1E25',
    borderRadius: 5,
    color: '#FFFF',
    padding: 16,
    fontSize: 16,
    marginRight: 12,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 24,
  },
  button: {
    width: 56,
    height: 56,
    borderRadius: 5,
    backgroundColor: '#1E6F9F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskList: {
    paddingHorizontal: 24,
    width: '100%',
    flex1: 1,
    marginTop: 32,
  },
  emptyContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyImage: {
    width: 56,
    height: 56,
    margin: 48,
  },
  emptyText: {
    color: '#808080',
    fontSize: 16,
    fontWeight: 'bold',
  },
  emptyTextSub: {
    color: '#797979',
    fontSize: 16,
    fontWeight: '400',
    marginTop: 8,
  },
});
